### ISSUE TITLE
[Frontend] Update to the Homepage

### ISSUE THREAD

**Issue by codenameobi** [BuildForSDG/Team-055-Frontend#11]
![send (1)](https://user-images.githubusercontent.com/44972479/84029556-7d3dbb00-a98a-11ea-9ab5-66c49a8aaf7d.PNG)
add the Find Help Link and change mobile navbar's color to something calmer to the user

**Comment by tay4real** [comment]
Issue resolved
![issue1](https://user-images.githubusercontent.com/53128146/84059499-a1ad8d80-a9b2-11ea-814f-1ba8cac07e4c.JPG)
